const squirrel=document.getElementById("squirrel"),magicBox=document.getElementById("magicBox"),registerShell=document.getElementById("registerShell"),storyCopy=document.getElementById("storyCopy"),storyTitle=document.getElementById("storyTitle"),storyText=document.getElementById("storyText"),progressBar=document.getElementById("progressBar"),leafLayer=document.getElementById("leafLayer"),replayBtn=document.getElementById("replayBtn"),musicBtn=document.getElementById("musicBtn"),musicLabel=document.getElementById("musicLabel"),closeBtn=document.getElementById("closeBtn"),againBtn=document.getElementById("againBtn"),form=document.getElementById("registerForm"),nameInput=document.getElementById("name"),emailInput=document.getElementById("email"),passwordInput=document.getElementById("password"),termsInput=document.getElementById("terms"),showPass=document.getElementById("showPass"),successName=document.getElementById("successName");
let timers=[],token=0,audioContext=null,masterGain=null,ambienceTimer=null,soundOn=false;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function clearTimers(){timers.forEach(clearTimeout);timers=[]}
function later(fn,ms){const id=setTimeout(fn,ms);timers.push(id);return id}
function setStory(t,p){storyTitle.textContent=t;storyText.textContent=p}
function createLeaf(){const l=document.createElement("i");l.className="falling-leaf";l.style.left=Math.random()*100+"%";l.style.animationDuration=5+Math.random()*5+"s";l.style.animationDelay=Math.random()*.7+"s";l.style.transform=`rotate(${Math.random()*90}deg) scale(${.65+Math.random()*.75})`;leafLayer.appendChild(l);setTimeout(()=>l.remove(),11000)}
function leafBurst(n=9){for(let i=0;i<n;i++)later(createLeaf,i*90)}
function resetVisuals(){clearTimers();token++;squirrel.classList.remove("walking");squirrel.style.left="23%";squirrel.style.transform="translateY(-390px)";magicBox.classList.remove("show","open");registerShell.classList.remove("show","success");registerShell.setAttribute("aria-hidden","true");storyCopy.classList.remove("hidden");setStory("Something is waking up...","Follow the little visitor.");progressBar.style.width="0%"}
async function runStory(){const t=++token;resetVisuals();await wait(500);if(t!==token)return;setStory("A little visitor is here...","Something moved in the old tree.");squirrel.style.transform="translateY(0)";leafBurst(5);progressBar.style.width="12%";await wait(1800);if(t!==token)return;setStory("What is that?","The squirrel spotted a mysterious box.");squirrel.classList.add("walking");squirrel.style.left=innerWidth<760?"46%":"52%";progressBar.style.width="29%";await wait(2100);if(t!==token)return;squirrel.classList.remove("walking");magicBox.classList.add("show");leafBurst(6);setStory("A mysterious box...","There might be something special inside.");progressBar.style.width="47%";await wait(1300);if(t!==token)return;squirrel.classList.add("walking");squirrel.style.left=innerWidth<760?"53%":"62%";setStory("Let's open it.","Curiosity wins.");progressBar.style.width="61%";await wait(1700);if(t!==token)return;squirrel.classList.remove("walking");magicBox.classList.add("open");leafBurst(10);setStory("Oh... hello! ✨","The box had a little surprise waiting.");progressBar.style.width="78%";await wait(1050);if(t!==token)return;storyCopy.classList.add("hidden");registerShell.classList.add("show");registerShell.setAttribute("aria-hidden","false");progressBar.style.width="100%";setTimeout(()=>nameInput.focus(),550)}
function restart(){resetVisuals();setTimeout(runStory,180)}
function closeRegistration(){registerShell.classList.remove("show","success");registerShell.setAttribute("aria-hidden","true");form.reset();clearErrors();setTimeout(()=>{storyCopy.classList.remove("hidden");setStory("The forest is waiting...","Replay the little story whenever you like.")},450)}
function clearErrors(){document.querySelectorAll(".error").forEach(e=>e.textContent="");document.querySelectorAll(".field input").forEach(e=>e.classList.remove("invalid"))}
function setError(input,id,msg){input.classList.add("invalid");document.getElementById(id).textContent=msg}
function validateForm(){clearErrors();let ok=true,n=nameInput.value.trim(),e=emailInput.value.trim(),p=passwordInput.value;if(n.length<2){setError(nameInput,"nameError","Please enter your full name.");ok=false}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)){setError(emailInput,"emailError","Please enter a valid email address.");ok=false}if(p.length<6){setError(passwordInput,"passwordError","Password must be at least 6 characters.");ok=false}if(!termsInput.checked){termsInput.parentElement.style.color="#c75c4d";ok=false}else termsInput.parentElement.style.color="";return ok}
form.addEventListener("submit",e=>{e.preventDefault();if(!validateForm())return;successName.textContent=nameInput.value.trim();registerShell.classList.add("success");playSuccessSound();confetti()});
showPass.addEventListener("click",()=>{const v=passwordInput.type==="text";passwordInput.type=v?"password":"text";showPass.textContent=v?"Show":"Hide"});
closeBtn.addEventListener("click",closeRegistration);againBtn.addEventListener("click",()=>{registerShell.classList.remove("success");form.reset();clearErrors();setTimeout(runStory,150)});replayBtn.addEventListener("click",restart);
function confetti(){const layer=document.createElement("div");layer.style.cssText="position:fixed;inset:0;pointer-events:none;z-index:100";for(let i=0;i<85;i++){const p=document.createElement("i"),x=(Math.random()-.5)*700,y=250+Math.random()*500,r=(Math.random()-.5)*900;p.style.cssText=`position:absolute;left:${45+Math.random()*10}%;top:${43+Math.random()*8}%;width:${5+Math.random()*5}px;height:${8+Math.random()*8}px;border-radius:${Math.random()>.5?"2px":"50%"};background:${["#6e9c5d","#d6a657","#d97958","#6d91b5","#9b6db0"][Math.floor(Math.random()*5)]}`;p.animate([{transform:"translate(0,0) rotate(0deg)",opacity:1},{transform:`translate(${x}px,${y}px) rotate(${r}deg)`,opacity:0}],{duration:1200+Math.random()*1100,easing:"cubic-bezier(.15,.7,.25,1)",fill:"forwards"});layer.appendChild(p)}document.body.appendChild(layer);setTimeout(()=>layer.remove(),2600)}
function startAudio(){if(soundOn)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;audioContext=audioContext||new A;if(audioContext.state==="suspended")audioContext.resume();masterGain=audioContext.createGain();masterGain.gain.value=.035;masterGain.connect(audioContext.destination);soundOn=true;musicLabel.textContent="Sound on";musicBtn.setAttribute("aria-pressed","true");playBell();ambienceTimer=setInterval(playBell,3600)}
function stopAudio(){soundOn=false;musicLabel.textContent="Sound off";musicBtn.setAttribute("aria-pressed","false");if(ambienceTimer){clearInterval(ambienceTimer);ambienceTimer=null}if(masterGain){masterGain.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.25);setTimeout(()=>{if(masterGain){masterGain.disconnect();masterGain=null}},300)}}
function playBell(){if(!soundOn||!audioContext||!masterGain)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type="sine";o.frequency.value=[392,523.25,659.25][Math.floor(Math.random()*3)];g.gain.setValueAtTime(.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.12,audioContext.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+1.2);o.connect(g);g.connect(masterGain);o.start();o.stop(audioContext.currentTime+1.25)}
function playSuccessSound(){if(!soundOn||!audioContext||!masterGain)return;[523.25,659.25,783.99].forEach((f,i)=>setTimeout(()=>{if(!soundOn)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type="sine";o.frequency.value=f;g.gain.setValueAtTime(.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.18,audioContext.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.55);o.connect(g);g.connect(masterGain);o.start();o.stop(audioContext.currentTime+.6)},i*130))}
musicBtn.addEventListener("click",()=>soundOn?stopAudio():startAudio());
window.addEventListener("load",runStory);
